apiVersion: v1
kind: ServiceAccount
metadata:
  name: est-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: est-service
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: est-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: est-service
subjects:
  - kind: ServiceAccount
    name: est-service
