#!/usr/bin/env bash
# Run EST Service Test Instance with HTTPS
# This script starts a local EST service instance with TLS enabled
# using the certificates generated by setup_backend.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config.sh"

# Configuration
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
EST_BINARY="${EST_BINARY:-$PROJECT_ROOT/bin/est-service}"
TEST_CONFIG="$TEST_DIR/est-service-test.yaml"
LOG_FILE="$TEST_DIR/est-service.log"

log_section "Starting EST Service Test Instance (HTTPS)"

# Check if setup has been run
if [ ! -f "$TEST_DIR/server-cert.pem" ] || [ ! -f "$TEST_DIR/server-key.pem" ]; then
    log_error "TLS certificates not found in $TEST_DIR"
    log_info "Please run setup_backend.sh first to generate certificates"
    exit 1
fi

# Check if EST service binary exists
if [ ! -f "$EST_BINARY" ]; then
    log_warn "EST service binary not found at: $EST_BINARY"
    log_info "Building EST service..."
    cd "$PROJECT_ROOT"
    make build
    if [ ! -f "$EST_BINARY" ]; then
        log_error "Failed to build EST service"
        exit 1
    fi
    log_success "EST service built successfully"
fi

# Create test configuration
log_info "Creating test configuration..."
cat > "$TEST_CONFIG" <<EOF
# EST Service Test Configuration - HTTPS Mode
# Auto-generated by run_test_instance.sh

server:
  listen_address: "127.0.0.1:8443"
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s
  rate_limit:
    enabled: false  # Disabled for testing
  tls:
    cert_file: "$TEST_DIR/server-cert.pem"
    key_file: "$TEST_DIR/server-key.pem"
    # Use combined CA bundle to trust both:
    # - Bootstrap certs (signed by client-ca) for initial enrollment
    # - Device certs (signed by PKI CA) for re-enrollment per RFC 7030
    client_ca_file: "$TEST_DIR/client-ca-bundle.pem"
    client_auth_type: "request"  # Accept but don't require client certs

# Backend: $BACKEND_TYPE
backend:
  type: "$BACKEND_TYPE"
  address: "$BACKEND_ADDR"
  tls_skip_verify: true
  
  # EST service's client certificate for authenticating to OpenBao
  # This certificate is used by the EST service to authenticate itself
  # to the backend via mTLS when cert auth is enabled
  client_cert: "$TEST_DIR/est-service-cert.pem"
  client_key: "$TEST_DIR/est-service-key.pem"
  
  timeout: 30s

est:
  enabled: true
  default_mount: "$PKI_PATH"

  default_policy:
    type: "role"
    value: "est-devices"

  authenticators:
    userpass:
      enabled: true
      mount_path: "userpass"
    cert:
      enabled: true
      mount_path: "cert"
      cert_role: "$CERT_AUTH_ROLE"
    token:
      enabled: false  # Not needed for EST protocol

  csr_validation:
    max_size_bytes: 32768

observability:
  logging:
    level: "debug"
    format: "json"
  metrics:
    enabled: false
  health:
    enabled: true

EOF

log_success "Configuration created: $TEST_CONFIG"

# Display configuration summary
log_section "Configuration Summary"
echo "  EST Service Binary: $EST_BINARY"
echo "  Configuration:      $TEST_CONFIG"
echo "  Listen Address:     https://127.0.0.1:8443"
echo "  TLS Certificate:    $TEST_DIR/server-cert.pem"
echo "  TLS Key:            $TEST_DIR/server-key.pem"
echo "  Client CA:          $TEST_DIR/client-ca.pem"
echo "  Backend Type:       $BACKEND_TYPE"
echo "  Backend Address:    $BACKEND_ADDR"
echo "  PKI Mount:          $PKI_PATH"
echo "  Log File:           $LOG_FILE"
echo ""

# Check if backend is accessible
log_info "Checking backend connectivity..."
if ! $BAO_CMD status > /dev/null 2>&1; then
    log_error "Cannot connect to $BACKEND_TYPE backend at $BACKEND_ADDR"
    log_info "Please ensure the backend is running and accessible"
    exit 1
fi
log_success "Backend is accessible"

# Check if port is already in use
if lsof -Pi :8443 -sTCP:LISTEN -t >/dev/null 2>&1 ; then
    log_warn "Port 8443 is already in use"
    log_info "Existing process on port 8443:"
    lsof -Pi :8443 -sTCP:LISTEN
    echo ""
    read -p "Kill existing process and continue? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        log_info "Killing existing process..."
        lsof -Pi :8443 -sTCP:LISTEN -t | xargs kill -9 2>/dev/null || true
        sleep 2
    else
        log_error "Exiting - port 8443 is in use"
        exit 1
    fi
fi

# Start EST service
log_section "Starting EST Service"

log_info "Starting EST service in background..."
log_info "Logs will be written to: $LOG_FILE"

# Start the service in background
"$EST_BINARY" -config "$TEST_CONFIG" > "$LOG_FILE" 2>&1 &
EST_PID=$!

# Save PID for later cleanup
echo "$EST_PID" > "$TEST_DIR/est-service.pid"

# Wait a moment for service to start
sleep 2

# Check if service is still running
if ! ps -p "$EST_PID" > /dev/null 2>&1; then
    log_error "EST service failed to start"
    log_info "Last 20 lines of log:"
    tail -20 "$LOG_FILE"
    exit 1
fi

# Wait for service to be ready
log_info "Waiting for service to be ready..."
MAX_WAIT=10
WAITED=0
while [ $WAITED -lt $MAX_WAIT ]; do
    if curl -sk "https://127.0.0.1:8443/.well-known/est/cacerts" > /dev/null 2>&1; then
        break
    fi
    sleep 1
    WAITED=$((WAITED + 1))
done

if [ $WAITED -ge $MAX_WAIT ]; then
    log_error "EST service did not become ready in time"
    log_info "Last 20 lines of log:"
    tail -20 "$LOG_FILE"
    kill "$EST_PID" 2>/dev/null || true
    exit 1
fi

log_success "EST service is running (PID: $EST_PID)"

log_section "Service Information"
echo "  ✓ EST Service URL:     https://127.0.0.1:8443"
echo "  ✓ Health Check:        https://127.0.0.1:8443/health"
echo "  ✓ CA Certificates:     https://127.0.0.1:8443/.well-known/est/cacerts"
echo "  ✓ Process ID:          $EST_PID"
echo "  ✓ Configuration:       $TEST_CONFIG"
echo "  ✓ Log File:            $LOG_FILE"
echo ""

log_section "Testing Service"
log_info "Fetching CA certificates..."
HTTP_CODE=$(curl -sk -o "$TEST_DIR/test-cacerts.b64" -w "%{http_code}" \
    "https://127.0.0.1:8443/.well-known/est/cacerts")

if [ "$HTTP_CODE" = "200" ]; then
    log_success "✓ Service is responding (HTTP $HTTP_CODE)"
else
    log_error "✗ Service returned HTTP $HTTP_CODE"
fi

log_section "Environment Variables"
echo "Export these variables to use the test instance:"
echo ""
echo "  export EST_SERVICE_ADDR=https://127.0.0.1:8443"
echo "  export EST_SERVICE_SKIP_VERIFY=true"
echo "  export BOOTSTRAP_CERT=$TEST_DIR/client-cert.pem"
echo "  export BOOTSTRAP_KEY=$TEST_DIR/client-key.pem"
echo ""

log_section "Available Test Scripts"
echo "Run these scripts to test the EST service:"
echo ""
echo "  # Test with username/password authentication:"
echo "  ./test/scripts/test_enrollment.sh"
echo ""
echo "  # Test with certificate authentication:"
echo "  ./test/scripts/test_enrollment_cert.sh"
echo ""

log_section "Service Management"
echo "To view logs in real-time:"
echo "  tail -f $LOG_FILE"
echo ""
echo "To stop the service:"
echo "  kill $EST_PID"
echo "  # or"
echo "  kill \$(cat $TEST_DIR/est-service.pid)"
echo ""
echo "To check service status:"
echo "  ps -p $EST_PID"
echo ""

log_info "Press Ctrl+C to stop the service, or run in background"

# Trap to cleanup on exit
cleanup_service() {
    log_info "Stopping EST service (PID: $EST_PID)..."
    kill "$EST_PID" 2>/dev/null || true
    wait "$EST_PID" 2>/dev/null || true
    log_success "EST service stopped"
}

# Ask if user wants to keep it running in background or foreground
echo ""
read -p "Keep service running in background? (Y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    log_success "EST service is running in background"
    log_info "PID saved to: $TEST_DIR/est-service.pid"
    log_info "Use 'kill $EST_PID' or the commands above to stop it"
else
    log_info "Keeping service in foreground. Press Ctrl+C to stop."
    trap cleanup_service EXIT INT TERM
    
    # Follow logs
    tail -f "$LOG_FILE" &
    TAIL_PID=$!
    
    # Wait for EST service to exit
    wait "$EST_PID" 2>/dev/null || true
    
    # Cleanup
    kill "$TAIL_PID" 2>/dev/null || true
fi
