// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "EST Service",
            "url": "https://github.com/mabunixda/est-service"
        },
        "license": {
            "name": "MPL-2.0",
            "url": "https://www.mozilla.org/en-US/MPL/2.0/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/.well-known/est/cacerts": {
            "get": {
                "description": "Retrieve the current CA certificate(s) used by the EST server. Returns a PKCS#7 certs-only structure containing one or more certificates.",
                "produces": [
                    "application/pkcs7-mime"
                ],
                "tags": [
                    "EST"
                ],
                "summary": "Get CA certificates",
                "responses": {
                    "200": {
                        "description": "CA certificates in base64-encoded PKCS#7 format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve CA certificates",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/.well-known/est/simpleenroll": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submit a Certificate Signing Request (CSR) to receive a signed certificate. Requires authentication via Basic Auth, TLS client certificate, or Bearer token.",
                "consumes": [
                    "application/pkcs10"
                ],
                "produces": [
                    "application/pkcs7-mime"
                ],
                "tags": [
                    "EST"
                ],
                "summary": "Enroll a new certificate",
                "parameters": [
                    {
                        "description": "Base64-encoded PKCS#10 Certificate Signing Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Signed certificate in base64-encoded PKCS#7 format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid CSR or CSR signature",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Enrollment failed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/.well-known/est/simplereenroll": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submit a Certificate Signing Request (CSR) to renew an existing certificate. Requires authentication and optionally validates that the CSR matches the client certificate.",
                "consumes": [
                    "application/pkcs10"
                ],
                "produces": [
                    "application/pkcs7-mime"
                ],
                "tags": [
                    "EST"
                ],
                "summary": "Reenroll an existing certificate",
                "parameters": [
                    {
                        "description": "Base64-encoded PKCS#10 Certificate Signing Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Renewed certificate in base64-encoded PKCS#7 format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid CSR, CSR signature, or CSR does not match client certificate",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Reenrollment failed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the service and backend are healthy and operational",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "$ref": "#/definitions/pkg_server.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service or backend unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Check if the service is ready to accept requests",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "Service is ready",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pkg_server.HealthResponse": {
            "type": "object",
            "properties": {
                "backend": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "tls_certificate": {
                    "$ref": "#/definitions/pkg_server.TLSCertInfo"
                }
            }
        },
        "pkg_server.TLSCertInfo": {
            "type": "object",
            "properties": {
                "days_remaining": {
                    "type": "integer"
                },
                "expires_at": {
                    "type": "string"
                },
                "status": {
                    "description": "\"ok\", \"warning\", \"critical\", \"expired\"",
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        },
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "EST protocol endpoints (RFC 7030)",
            "name": "EST"
        },
        {
            "description": "Health and readiness checks",
            "name": "Health"
        },
        {
            "description": "Observability endpoints",
            "name": "Metrics"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8443",
	BasePath:         "/",
	Schemes:          []string{"https", "http"},
	Title:            "EST Service API",
	Description:      "Enrollment over Secure Transport (EST) Service implementing RFC 7030.\nThis service provides a standards-compliant EST implementation that uses OpenBao or HashiCorp Vault as the backend PKI system.\n\n**Authentication Methods:**\n- HTTP Basic Auth (mapped to backend userpass, LDAP, or AppRole)\n- TLS Client Certificates (mapped to backend cert auth)\n- Bearer Token (backend token authentication)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
